name: clean_architecture
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.2
  google_fonts: ^4.0.4
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  lint: ^2.1.2
  retrofit_generator: ^7.0.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
